---

- name: Create Bamboo dir dependencies
  file: path={{ item }}
        state=directory
  with_items:
    - /var/atlassian/application-data
    - "{{ bambooData }}"
  sudo: yes

- name: create bamboo user
  user: name={{ bambooUser }}
        comment="Atlassian BAMBOO"
        home=/var/atlassian/application-data/bamboo/
        shell=/bin/bash
  sudo: yes

- name: Download Bamboo
  get_url: url={{ bambooUrl }}
           dest=/tmp
  sudo: yes

- name: Unpack Bamboo
  unarchive: src=/tmp/{{ bambooTarFile }}
             dest=/tmp
             copy=false
  sudo: yes

- name: Move Bamboo
  raw: mv /tmp/atlassian-bamboo-5.8.1/* {{ bambooData }}
  sudo: yes

- name: debug bamboo
  raw: ls -al /opt/atlassian/bamboo
  register: dbv

- name: print debug
  debug: var=dbv

- name: Download local JRE source files
  get_url: url=http://files.configure.systems/jre.tar.gz
           dest=/tmp/jre.tar.gz
  sudo: yes

- unarchive: src=/tmp/jre.tar.gz
             dest=/tmp
             copy=false
  sudo: yes

- name: Move JRE
  raw: mv /tmp/jre {{ bambooData }}/jre
  sudo: yes

- name: debug bamboo
  raw: ls -al /opt/atlassian/bamboo/jre
  register: dbv

- name: print debug
  debug: var=dbv

- name: Download MySQL Connector
  get_url: url={{ mysqlConnectorUrl }}
           dest={{ bambooData }}/lib/{{ mysqlConnectorJar }}
  sudo: yes

- name: Set Perms on Bamboo Data Dir
  file: path={{ bambooData }}
        owner={{ bambooUser }}
        group=root
  sudo: yes
 
- name: Copy bamboo init.d File
  template: src=bamboo.init.d.j2
            dest=/etc/init.d/atlbamboo
            mode=0755
  sudo: yes

- name: debug bamboo
  raw: ls -al /etc/init.d/
  register: dbv

- name: print debug
  debug: var=dbv

- name: stop bamboo
  raw: /etc/init.d/altbamboo stop
  sudo: yes

- name: simulate long running op (30 sec), wait for up to 75 sec, poll every 5 sec
  command: /bin/sleep 30
  async: 75
  poll: 5

- name: start bamboo
  raw: /etc/init.d/altbamboo start
  sudo: yes
